use crate::detect::Detection;

pub fn generate_crushfile(detection: &Detection) -> String {
    let mut toml = String::new();

    toml.push_str("# Crushfile — auto-generated by `crush`\n");
    toml.push_str("# Inferred fields are marked; edit as needed.\n\n");

    toml.push_str("[project]\n");
    toml.push_str(&format!("name = \"{}\"  # inferred\n", detection.project_name));
    toml.push_str(&format!("type = \"{}\"  # inferred\n", detection.runtime_type.as_str()));
    toml.push_str(&format!("runtime = \"{}\"  # inferred\n", detection.runtime_version));
    toml.push_str(&format!("confidence = {:.2}  # auto-detection confidence\n\n", detection.confidence));

    toml.push_str("[build]\n");
    toml.push_str(&format!("command = \"{}\"  # inferred\n", detection.build_command));
    toml.push_str(&format!("entry = \"{}\"  # inferred\n", detection.entry_point));
    toml.push_str(&format!("port = {}\n\n", detection.port));

    if !detection.env_required.is_empty() {
        toml.push_str("[env]\n");
        toml.push_str("# Required environment variables\n");
        for env in &detection.env_required {
            toml.push_str(&format!("# {} = \"\"\n", env));
        }
        toml.push_str("\n");
    }

    if !detection.env_optional.is_empty() {
        toml.push_str("# Optional environment variables\n");
        for env in &detection.env_optional {
            toml.push_str(&format!("# {} = \"\"\n", env));
        }
        toml.push_str("\n");
    }

    if detection.framework_detected {
        toml.push_str(&format!("# Detected framework: {}\n", detection.framework_name));
    }

    if detection.is_monorepo {
        toml.push_str("\n# Monorepo workspace detected\n");
        for (i, service) in detection.services.iter().enumerate() {
            toml.push_str(&format!("# Service {}: {} (path: {})\n", i + 1, service.name, service.path));
        }
    }

    if let Some(ref dockerfile) = detection.dockerfile_found {
        toml.push_str(&format!("\n# Dockerfile found: {}\n", dockerfile));
        toml.push_str("# Compat mode: translating Docker instructions\n");
    }

    toml
}
